apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: usgs-event-source
spec:
  image: docker.io/gswk/usgs-event-source:cloudevents
  args: 
    - "--interval=10"
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default